apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sock-shop-scraper-session-db
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - sock-shop
  selector:
    matchLabels:
      name: session-db
  endpoints:
  - path: /metrics
  - interval: 30s
